import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Footer from '@/components/Footer'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        
        <div className={styles.xlogo}>
          <Image src={'/images/logo-x.svg'} alt='Logo' width={350} height={350}/>
        </div>

        <div className={styles.content}>
          <h1 className={`${styles.h1}`}>Happening now</h1>
          <h2 className={`${styles.h2}`}>Join today.</h2>
        
        <button className={styles.Googlebtn}>
        <Image className={styles.googleImg} src={'/images/google-logo.png'} width={20} height={20}/>
          <span>Sign up with Google</span>
        </button>
        <button className={styles.Applebtn}>
          <Image className={styles.appleImg} src={'/images/apple-logo.png'} width={18} height={20}/>
          <span>Sign up with Apple</span>
        </button>

        <p className={styles.or}>––––––––––––––– or ––––––––––––––– </p>

        
        <button className={styles.createAccount}>
          <span>Create account</span>
        </button>

        <p className={styles.terms}>By signing up, you agree to the <a href="#"> Terms of Service </a> and <a href="#"> Privacy Policy</a>, <br/> including <a href="#">Cookie Use.</a></p>

        <h3 className={styles.h3}>Already have an account?</h3>

        <button className={styles.signIn}>
          <span>Sign in</span>
        </button>
        </div>




      
      </main>
     <Footer/>
    </>
  )
}
